### ISSUE TITLE
Container Image?

### ISSUE THREAD

**Issue by cevich** [JungWinter/comment#2]
Hi,

Thanks for writing this github action, I'm using and appreciating it.  Especially the ability to edit a comment, it cuts down on clutter.  One suggestion:  I noticed the action is building the dockerfile every time, this is not only slow, but could be less reliable / stable if some secondary service breaks.

I would suggest doing at least one container image build per release, and pushing it to a registry somewhere (like docker hub.  This will be faster for users, and more stable/reliable.

Also, in case it's a useful example, here's a [workflow I'm using to both push releases, and build+push a container image](https://github.com/containers/automation/blob/7612ca4ea472913410268343042b519eded125ef/.github/workflows/release.yml)

**Comment by winterjung** [comment]
Thanks for your great suggestion! I didn't know I can use docker registry. I'll push my `comment` docker image with `v1`, `latest`, `master` tag as soon as possible!

**Comment by cevich** [comment]
oh that would be excellent.  Then all that's needed is to reference it in the `action.yml` instead of the Dockerfile.  This will be a big benefit to all users, since pulling the image is MUCH faster than building it.  Thanks!

**Comment by cevich** [comment]
Ref: https://help.github.com/en/actions/building-actions/metadata-syntax-for-github-actions#example-using-public-docker-registry-container
