### ISSUE TITLE
Actions has been renamed to winterjung/comment

### ISSUE THREAD

**Issue by fstehle** [JungWinter/comment#7]
The action seems to fail now. We get the following error:
```
Error: Unable to resolve action. Repository not found: JungWinter/comment
```

Was the repository or github profile name changed?

**Comment by winterjung** [comment]
Sorry for breaking changes. I recently changed my github name. After changing the name, the JungWinter/comment repo was redirected to winterjung/comment, so I thought there would be no problem but It wasn't. Please rename the repo name to `winterjung/comment@v1`. I will also update readme soon.
